// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwkjdbrdwvutbtpxsjck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3a2pkYnJkd3Z1dGJ0cHhzamNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjM2MTUsImV4cCI6MjA2NDc5OTYxNX0.QMsPy7yEYgIZIm9SmatvQBZWMvjFRsmnaRFb3HHyjBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);